/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyectobase;

import proyectobase.Casting;
import proyectobase.Conditionals;
import proyectobase.StringLesson;
import proyectobase.MathLesson;
import oop.MainClass;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Casting casting = new Casting();
        StringLesson string = new StringLesson();
        MathLesson math = new MathLesson();
        Conditionals conditionals = new Conditionals();

        System.out.println(new App().getGreeting());
        MainClass.myStaticMethod(); //Llama al metodo sin la necesidad de instanciar a algun objeto (IMPORTANTE)
    }
}
