/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyectobase;

import other_classes.ArrayListClass;
import other_classes.JavaIterator;
import other_classes.Map;
import proyectobase.Casting;
import proyectobase.Conditionals;
import proyectobase.StringLesson;
import proyectobase.MathLesson;
import oop.Demarcacion;
import oop.Equipo;
import oop.ImplementingClass;
import oop.InheritedClass;
import oop.InnerClass;
import oop.MainClass;
import oop.InnerClass.InnerClass2;

import java.util.HashMap;

public class App {
    public static void main(String[] args) {
        /* Casting casting = new Casting();
        StringLesson string = new StringLesson();
        MathLesson math = new MathLesson();
        Conditionals conditionals = new Conditionals();

        System.out.println(new App().getGreeting());
        MainClass.myStaticMethod(); // Llama al metodo sin la necesidad de instanciar a algun objeto (IMPORTANTE)

        // NOVEDADES DEL OOP
        // CLASES ANIDADAS
        InnerClass claseGrande = new InnerClass();
        InnerClass.InnerClass2 claseChiquita = claseGrande.new InnerClass2(); // Que forma tan curiosita la vdd XD
        System.out.println("Suma de innre y outer: " + claseGrande.outterNumber + claseChiquita.innerNumber);

        // CLASES ABSTRACTAS
        InheritedClass claseNoAbstracta = new InheritedClass();
        claseNoAbstracta.abstractPrint();

        // INTERFACES
        ImplementingClass implementing = new ImplementingClass();
        implementing.interfaceMethod1();
        implementing.interfaceMethod2();

        // ENUMS
        Demarcacion delattr = Demarcacion.DELANTERO;
        System.out.println(delattr.name()); // Devuelve un String con el nombre de la constante (DELANTERO)
        System.out.println(delattr.toString()); // Devuelve un String con el nombre de la constante (DELANTERO)
        System.out.println(delattr.ordinal()); // Devuelve un entero con la posición del enum
        System.out.println(Demarcacion.values());

        Equipo equipo = Equipo.BARCA; // Enum con argumentos por cada valor
        System.out.println(equipo.getNombreClub());
        System.out.println(equipo.getPuestoLiga());
        */

        // CONTENEDORES DE DATOS
        ArrayListClass customArrayList = new ArrayListClass();
        Map customMap = new Map();

        //Iteracion usando un iterador personalizado
        JavaIterator.globalIterator = customArrayList.cars.iterator(); //Cada contenedor tiene la propiedad iterator
        System.out.println(JavaIterator.globalIterator.hasNext()); //Imprime el primer item si es que existe (VERIFICACION) + USO DE WHILE PARA ITERAR MIENTRAS EXISTA UN ELEMENTO


    }

    public String getGreeting() {
        return "Hello World!";
    }
}
