server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/B1nast1c/Java-Learning-Path
          search-paths: config-data
  application:
    name: ConfigServerSpring