spring:
    application:
        name: GatewaySpring
    cloud:
        config:
            enabled: true
            uri: http://localhost:8000
        gateway:
            routes:
                - id: employee-route
                  uri: http://localhost:8080
                  predicates:
                    - Path=/employees/**
                  filters:
                    - PrefixPath=/api
                - id: users-route
                  uri: http://localhost:8081
                  predicates:
                    - Path=/users/**
                  filters:
                    - PrefixPath=/api
    config:
        import: 'configserver:'