server:
  port: 8080
spring:
  application:
    name: SpringBoot
  datasource:
    password: 72163252Ulasalle.
    url: jdbc:mysql://localhost:3306/employees
    username: root
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: update